<?php

namespace App\Http\Requests\Api\Filter;

use App\Models\Filter;
use Illuminate\Foundation\Http\FormRequest;

class StoreRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            'title' => 'required|string',
            'entity_id' => 'required|exists:entities,id',
            'is_default' => 'boolean',
            'is_required' => 'boolean',
            'type' => 'in:'.implode(',', Filter::FIELDS)

        ];
    }

    public function messages()
    {
        return parent::messages(); // TODO: Change the autogenerated stub
    }
}
